[workspace]

members = [
  "planning_poker",
  "substrings_between",
  "add_two_numbers",
  "shopping_cart",
  "count_words",
  "left_pad",
  "tax_calculator",
  "passing_grade",
  "unique",
  "index_of",
  "stubbing_invoices",
  "stubbing_external_service",
  "date_and_time_wrappers"
]