[package]
name = "date_and_time_wrappers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
mockall_double = "0.2.1"

[dev-dependencies]
mockall = "0.11.0"

