[package]
name = "testing_larger_components_shopping_cart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.3.0"
typed-builder = "0.10.0"


[dev-dependencies]
mockall = "0.11.0"
